/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.ukrcom.onlinemanager;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.font.TextAttribute;
import java.sql.SQLException;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author olden
 */
public class gridOnline extends javax.swing.JPanel {

    /**
     * Creates new form gridOnline
     */
    public gridOnline() {

        initComponents();

        jCutCopyPaste jCopy = new jCutCopyPaste();
        jCopy.jMenuItemPopupCut.setEnabled(false);
        jCopy.jMenuItemPopupPaste.setEnabled(false);
        this.jTextFieldRadiusID.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldUsername.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldRouter.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldSessionID.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldStartTIme.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldUpdateTime.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldStopTime.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldFramedIP.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldLinkTime.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldCustomerName.setComponentPopupMenu(jCopy.jPopupMenu);
        this.jTextFieldCustomerLocation.setComponentPopupMenu(jCopy.jPopupMenu);

        jCutCopyPaste jCutCopyPaste = new jCutCopyPaste();
        this.jFormattedTextFieldDays.setComponentPopupMenu(jCutCopyPaste.jPopupMenu);
        this.jTextFieldCustomerFilter.setComponentPopupMenu(jCutCopyPaste.jPopupMenu);
        this.jTextFieldUsernameAndFramedIPFilter.setComponentPopupMenu(jCutCopyPaste.jPopupMenu);
        if (!java.beans.Beans.isDesignTime()) {
            this.loadData();
        }
        this.jTextFieldCustomerFilter.requestFocus();

//        this.showCell(0, 0);
    }

    public static class BeanInfo extends java.beans.SimpleBeanInfo {

        @Override
        public java.awt.Image getIcon(int iconType) {
            return null; // або поверни іконку, якщо хочеш
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTableOnline = new javax.swing.JPanel();
        jScrollPaneTableOnline = new javax.swing.JScrollPane();
        jTableOnline = new javax.swing.JTable();
        jPanelBottom = new javax.swing.JPanel();
        jPanelDetail = new javax.swing.JPanel();
        jLabelRadiusID = new javax.swing.JLabel();
        jTextFieldRadiusID = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelRouter = new javax.swing.JLabel();
        jTextFieldRouter = new javax.swing.JTextField();
        jLabelSessionID = new javax.swing.JLabel();
        jTextFieldSessionID = new javax.swing.JTextField();
        jLabelStartTIme = new javax.swing.JLabel();
        jTextFieldStartTIme = new javax.swing.JTextField();
        jLabelUpdateTime = new javax.swing.JLabel();
        jTextFieldUpdateTime = new javax.swing.JTextField();
        jLabelStopTime = new javax.swing.JLabel();
        jTextFieldStopTime = new javax.swing.JTextField();
        jLabelFramedIP = new javax.swing.JLabel();
        jTextFieldFramedIP = new javax.swing.JTextField();
        jLabelLinkTime = new javax.swing.JLabel();
        jTextFieldLinkTime = new javax.swing.JTextField();
        jLabelCustomerName = new javax.swing.JLabel();
        jTextFieldCustomerName = new javax.swing.JTextField();
        jLabelCustomerLocation = new javax.swing.JLabel();
        jTextFieldCustomerLocation = new javax.swing.JTextField();
        jPanelFilter = new javax.swing.JPanel();
        jPanelOnlyActiveFilter = new javax.swing.JPanel();
        jCheckBoxOnline = new javax.swing.JCheckBox();
        jPanelLastDays = new javax.swing.JPanel();
        jLabelFilterLastDays1 = new javax.swing.JLabel();
        jFormattedTextFieldDays = new javax.swing.JFormattedTextField();
        jLabelFilterLastDays2 = new javax.swing.JLabel();
        jPanelUsernameAndFramedIPFilter = new javax.swing.JPanel();
        jLabelUsernameAndFramedIPFilter = new javax.swing.JLabel();
        jTextFieldUsernameAndFramedIPFilter = new javax.swing.JTextField();
        jWhereOperation = new javax.swing.JComboBox<>();
        jButtonUsernameAndFramedIPFilter = new javax.swing.JButton();
        jPanelCustomerFilter = new javax.swing.JPanel();
        jLabelCustomerFilter = new javax.swing.JLabel();
        jTextFieldCustomerFilter = new javax.swing.JTextField();
        jButtonClearCustomerFilter = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(1000, 400));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanelTableOnline.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTableOnline.setLayout(new javax.swing.OverlayLayout(jPanelTableOnline));

        jTableOnline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "radacctid", "username", "router", "sessionid", "acctstarttime", "acctupdatetime", "acctstoptime", "framedipaddress", "dt", "customername", "location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOnline.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableOnline.setShowGrid(false);
        jTableOnline.setShowHorizontalLines(true);
        TableColumn column;
        column = jTableOnline.getColumnModel().getColumn(0);
        column.setWidth(0);
        column.setMinWidth(0);
        column.setMaxWidth(0);
        //jTableOnline.removeColumn(column);

        column = jTableOnline.getColumnModel().getColumn(8);
        column.setWidth(0);
        column.setMinWidth(0);
        column.setMaxWidth(0);

        jTableOnline.setDefaultRenderer(String.class, new ImageTextCellRenderer());
        jTableOnline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOnlineMouseClicked(evt);
            }
        });
        jTableOnline.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableOnlineKeyReleased(evt);
            }
        });
        jScrollPaneTableOnline.setViewportView(jTableOnline);

        jPanelTableOnline.add(jScrollPaneTableOnline);

        add(jPanelTableOnline);

        jPanelBottom.setMaximumSize(new java.awt.Dimension(32767, 320));
        jPanelBottom.setMinimumSize(new java.awt.Dimension(1046, 320));
        jPanelBottom.setPreferredSize(new java.awt.Dimension(1046, 320));
        jPanelBottom.setLayout(new java.awt.GridLayout(1, 2));

        jPanelDetail.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 5));
        jPanelDetail.setLayout(new java.awt.GridLayout(11, 2, 4, 2));

        jLabelRadiusID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRadiusID.setText("RadiusID");
        jPanelDetail.add(jLabelRadiusID);

        jTextFieldRadiusID.setEditable(false);
        jTextFieldRadiusID.setBackground(new java.awt.Color(250, 250, 250));
        jPanelDetail.add(jTextFieldRadiusID);

        jLabelUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsername.setLabelFor(jTextFieldUsername);
        jLabelUsername.setText("Username");
        jPanelDetail.add(jLabelUsername);

        jTextFieldUsername.setEditable(false);
        jTextFieldUsername.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetail.add(jTextFieldUsername);

        jLabelRouter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRouter.setLabelFor(jTextFieldRouter);
        jLabelRouter.setText("Router");
        jPanelDetail.add(jLabelRouter);

        jTextFieldRouter.setEditable(false);
        jTextFieldRouter.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetail.add(jTextFieldRouter);

        jLabelSessionID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSessionID.setLabelFor(jTextFieldSessionID);
        jLabelSessionID.setText("Session ID");
        jPanelDetail.add(jLabelSessionID);

        jTextFieldSessionID.setEditable(false);
        jTextFieldSessionID.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetail.add(jTextFieldSessionID);

        jLabelStartTIme.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelStartTIme.setLabelFor(jTextFieldStartTIme);
        jLabelStartTIme.setText("Start Time");
        jPanelDetail.add(jLabelStartTIme);

        jTextFieldStartTIme.setEditable(false);
        jTextFieldStartTIme.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetail.add(jTextFieldStartTIme);

        jLabelUpdateTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUpdateTime.setLabelFor(jTextFieldUpdateTime);
        jLabelUpdateTime.setText("Update Time");
        jPanelDetail.add(jLabelUpdateTime);

        jTextFieldUpdateTime.setEditable(false);
        jTextFieldUpdateTime.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetail.add(jTextFieldUpdateTime);

        jLabelStopTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelStopTime.setLabelFor(jTextFieldStopTime);
        jLabelStopTime.setText("Stop Time");
        jPanelDetail.add(jLabelStopTime);

        jTextFieldStopTime.setEditable(false);
        jTextFieldStopTime.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetail.add(jTextFieldStopTime);

        jLabelFramedIP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFramedIP.setLabelFor(jTextFieldFramedIP);
        jLabelFramedIP.setText("IP Address");
        jPanelDetail.add(jLabelFramedIP);

        jTextFieldFramedIP.setEditable(false);
        jTextFieldFramedIP.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetail.add(jTextFieldFramedIP);

        jLabelLinkTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLinkTime.setLabelFor(jTextFieldLinkTime);
        jLabelLinkTime.setText("Link Time");
        jLabelLinkTime.setToolTipText("Displays the time when the association between Username and Customer was made.");
        jPanelDetail.add(jLabelLinkTime);

        jTextFieldLinkTime.setEditable(false);
        jTextFieldLinkTime.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldLinkTime.setToolTipText("Displays the time when the association between Username and Customer was made.");
        jPanelDetail.add(jTextFieldLinkTime);

        jLabelCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCustomerName.setLabelFor(jTextFieldCustomerName);
        jLabelCustomerName.setText("Customer Name");
        jPanelDetail.add(jLabelCustomerName);

        jTextFieldCustomerName.setEditable(false);
        jTextFieldCustomerName.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetail.add(jTextFieldCustomerName);

        jLabelCustomerLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCustomerLocation.setLabelFor(jTextFieldCustomerLocation);
        jLabelCustomerLocation.setText("Customer Location");
        jPanelDetail.add(jLabelCustomerLocation);

        jTextFieldCustomerLocation.setEditable(false);
        jTextFieldCustomerLocation.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetail.add(jTextFieldCustomerLocation);

        jPanelBottom.add(jPanelDetail);

        jPanelFilter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 5));
        jPanelFilter.setLayout(new java.awt.GridLayout(11, 1, 4, 2));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        jPanelOnlyActiveFilter.setLayout(flowLayout1);

        jCheckBoxOnline.setBackground(new java.awt.Color(255, 0, 0));
        jCheckBoxOnline.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jCheckBoxOnline.setText("Show only active (not closed) sessions.");
        jCheckBoxOnline.setToolTipText("Only online users");
        jCheckBoxOnline.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        jCheckBoxOnline.setMinimumSize(new java.awt.Dimension(269, 22));
        jCheckBoxOnline.addActionListener(this::jCheckBoxOnlineActionPerformed);
        jPanelOnlyActiveFilter.add(jCheckBoxOnline);

        jPanelFilter.add(jPanelOnlyActiveFilter);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        jPanelLastDays.setLayout(flowLayout2);

        jLabelFilterLastDays1.setText("Show inactive sessions only from the last ");
        jPanelLastDays.add(jLabelFilterLastDays1);

        jFormattedTextFieldDays.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldDays.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldDays.setToolTipText("Closed sessions are no older than the specified number of days");
        jFormattedTextFieldDays.setMaximumSize(new java.awt.Dimension(65, 22));
        jFormattedTextFieldDays.setMinimumSize(new java.awt.Dimension(65, 22));
        jFormattedTextFieldDays.setPreferredSize(new java.awt.Dimension(65, 22));
        jFormattedTextFieldDays.setValue(1);
        jPanelLastDays.add(jFormattedTextFieldDays);

        jLabelFilterLastDays2.setText(" day(s).");
        jPanelLastDays.add(jLabelFilterLastDays2);

        jPanelFilter.add(jPanelLastDays);

        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout3.setAlignOnBaseline(true);
        jPanelUsernameAndFramedIPFilter.setLayout(flowLayout3);

        jLabelUsernameAndFramedIPFilter.setText("Username or FramedIP filter");
        jPanelUsernameAndFramedIPFilter.add(jLabelUsernameAndFramedIPFilter);

        jTextFieldUsernameAndFramedIPFilter.setToolTipText("Filter by Username or FramedIP");
        jTextFieldUsernameAndFramedIPFilter.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        jTextFieldUsernameAndFramedIPFilter.setMinimumSize(new java.awt.Dimension(300, 22));
        jTextFieldUsernameAndFramedIPFilter.setPreferredSize(new java.awt.Dimension(300, 22));
        jPanelUsernameAndFramedIPFilter.add(jTextFieldUsernameAndFramedIPFilter);

        jWhereOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIKE", "=" }));
        jWhereOperation.setToolTipText("Operation for IP-address comparison");
        jPanelUsernameAndFramedIPFilter.add(jWhereOperation);

        jButtonUsernameAndFramedIPFilter.setText("❌");
        jButtonUsernameAndFramedIPFilter.setToolTipText("Clear customer filter");
        jButtonUsernameAndFramedIPFilter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonUsernameAndFramedIPFilter.setMaximumSize(new java.awt.Dimension(22, 22));
        jButtonUsernameAndFramedIPFilter.setMinimumSize(new java.awt.Dimension(22, 22));
        jButtonUsernameAndFramedIPFilter.setPreferredSize(new java.awt.Dimension(22, 22));
        jButtonUsernameAndFramedIPFilter.addActionListener(this::jButtonUsernameAndFramedIPFilterActionPerformed);
        jPanelUsernameAndFramedIPFilter.add(jButtonUsernameAndFramedIPFilter);

        jPanelFilter.add(jPanelUsernameAndFramedIPFilter);

        java.awt.FlowLayout flowLayout4 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout4.setAlignOnBaseline(true);
        jPanelCustomerFilter.setLayout(flowLayout4);

        jLabelCustomerFilter.setText("Customer filter");
        jPanelCustomerFilter.add(jLabelCustomerFilter);

        jTextFieldCustomerFilter.setToolTipText("Filter by customer name");
        jTextFieldCustomerFilter.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        jTextFieldCustomerFilter.setMinimumSize(new java.awt.Dimension(305, 22));
        jTextFieldCustomerFilter.setPreferredSize(new java.awt.Dimension(305, 22));
        jPanelCustomerFilter.add(jTextFieldCustomerFilter);

        jButtonClearCustomerFilter.setText("❌");
        jButtonClearCustomerFilter.setToolTipText("Clear customer filter");
        jButtonClearCustomerFilter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonClearCustomerFilter.setMaximumSize(new java.awt.Dimension(22, 22));
        jButtonClearCustomerFilter.setMinimumSize(new java.awt.Dimension(22, 22));
        jButtonClearCustomerFilter.setPreferredSize(new java.awt.Dimension(22, 22));
        jButtonClearCustomerFilter.addActionListener(this::jButtonClearCustomerFilterActionPerformed);
        jPanelCustomerFilter.add(jButtonClearCustomerFilter);

        jButtonRefresh.setMnemonic('R');
        jButtonRefresh.setText("⟳ Run!");
        jButtonRefresh.setToolTipText("Refresh");
        jButtonRefresh.addActionListener(this::jButtonRefreshActionPerformed);
        jPanelCustomerFilter.add(jButtonRefresh);

        jPanelFilter.add(jPanelCustomerFilter);

        jPanelBottom.add(jPanelFilter);

        add(jPanelBottom);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableOnlineKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableOnlineKeyReleased
        this.jTableOnlineSelectRow(
                jTableOnline.getSelectedRow()
        );
    }//GEN-LAST:event_jTableOnlineKeyReleased

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        this.loadData();
        this.jTextFieldCustomerFilter.requestFocus();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jCheckBoxOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOnlineActionPerformed
        if (this.jCheckBoxOnline.isSelected()) {
            this.jCheckBoxOnline.setBackground(this.jLabelFilterLastDays1.getBackground());
            this.jFormattedTextFieldDays.setEnabled(false);
        } else {
            this.jCheckBoxOnline.setBackground(new java.awt.Color(255, 0, 0));
            this.jFormattedTextFieldDays.setEnabled(true);
        }
        this.loadData();
        this.jTextFieldCustomerFilter.requestFocus();
    }//GEN-LAST:event_jCheckBoxOnlineActionPerformed

    private void jButtonClearCustomerFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearCustomerFilterActionPerformed
        this.jTextFieldCustomerFilter.setText("");
        this.loadData();
        this.jTextFieldCustomerFilter.requestFocus();
    }//GEN-LAST:event_jButtonClearCustomerFilterActionPerformed

    private void jButtonUsernameAndFramedIPFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsernameAndFramedIPFilterActionPerformed
        this.jTextFieldUsernameAndFramedIPFilter.setText("");
        this.loadData();
        this.jTextFieldUsernameAndFramedIPFilter.requestFocus();
    }//GEN-LAST:event_jButtonUsernameAndFramedIPFilterActionPerformed

    private void jTableOnlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOnlineMouseClicked
        this.jTableOnlineSelectRow(
                jTableOnline.getSelectedRow()
        );
    }//GEN-LAST:event_jTableOnlineMouseClicked

    public void loadData() {
        try {
            /*
            System.err.print(jWhereOperation.getSelectedIndex() + " -> ");
            System.err.println(String.valueOf(jWhereOperation.getSelectedItem()));
             */
            RadiusData radiusData = RadiusData.getInstance()
                    .getData(
                            (DefaultTableModel) jTableOnline.getModel(),
                            Integer.parseInt(this.jFormattedTextFieldDays.getText().trim()),
                            this.jCheckBoxOnline.isSelected(),
                            this.jWhereOperation.getSelectedIndex(),
                            this.jTextFieldCustomerFilter.getText().trim(),
                            this.jTextFieldUsernameAndFramedIPFilter.getText().trim()
                    );
        } catch (SQLException ex) {
            Logger.getLogger(gridOnline.class.getName()).log(Level.SEVERE, null, ex);
        }
        int rowCount = jTableOnline.getRowCount() - 1;
        this.jTableOnlineSelectRow(rowCount);
    }

    public int showCell(int row, int column) {
        Rectangle rect = jTableOnline.getCellRect(row, column, true);
        this.jTableOnline.scrollRectToVisible(rect);
        this.jTableOnline.clearSelection();
        if (row >= 0) {
            this.jTableOnline.setRowSelectionInterval(row, row);
        }
        return row;
    }

    public void jTableOnlineSelectRow(int selectedRow) {
//        System.err.println(selectedRow + " " + this.jTableOnline.getRowCount());
        if (this.showCell(selectedRow, selectedRow) >= 0) {
            this.jTextFieldRadiusID.setText((String) jTableOnline.getValueAt(selectedRow, 0));
            this.jTextFieldUsername.setText((String) jTableOnline.getValueAt(selectedRow, 1));
            this.jTextFieldRouter.setText((String) jTableOnline.getValueAt(selectedRow, 2));
            this.jTextFieldSessionID.setText((String) jTableOnline.getValueAt(selectedRow, 3).toString());
            this.jTextFieldStartTIme.setText((String) jTableOnline.getValueAt(selectedRow, 4));
            this.jTextFieldUpdateTime.setText((String) jTableOnline.getValueAt(selectedRow, 5));
            this.jTextFieldStopTime.setText((String) jTableOnline.getValueAt(selectedRow, 6));
            this.jTextFieldFramedIP.setText((String) jTableOnline.getValueAt(selectedRow, 7));
            this.jTextFieldLinkTime.setText((String) jTableOnline.getValueAt(selectedRow, 8));
            this.jTextFieldCustomerName.setText((String) jTableOnline.getValueAt(selectedRow, 9));
            this.jTextFieldCustomerLocation.setText((String) jTableOnline.getValueAt(selectedRow, 10));
        }
    }

    class ImageTextCellRenderer extends DefaultTableCellRenderer {

        Color backgroundColor = getBackground();

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            String text = (String) value;
            JLabel label = (JLabel) super.getTableCellRendererComponent(table, text, isSelected, hasFocus, row, column);
            switch (column) {
                case 1, 9, 10 -> {
                    label.setHorizontalAlignment(JLabel.LEFT);
                    Font font = label.getFont().deriveFont(
                            Collections.singletonMap(TextAttribute.WEIGHT, TextAttribute.WEIGHT_ULTRABOLD)
                    );
                    label.setFont(font);
                }
                case 3 ->
                    label.setHorizontalAlignment(JLabel.RIGHT);
                case 4, 5, 6, 7, 8 ->
                    label.setHorizontalAlignment(JLabel.CENTER);
                default ->
                    label.setHorizontalAlignment(JLabel.LEFT);
            }

            String jStopTime = (String) jTableOnline.getValueAt(row, 6);
            String jCustomName = (String) jTableOnline.getValueAt(row, 9);

            if (!isSelected) {
                label.setBackground(backgroundColor);
            }
            if (jStopTime == null) {
                label.setForeground(Color.darkGray);
                if (jCustomName != null) {
                    label.setBackground(Color.green.brighter());
                } else {
                    label.setBackground(Color.green.darker());
                }
            } else {
                label.setForeground(Color.black.brighter());
                if (jCustomName != null) {
                    label.setBackground(Color.yellow.brighter());
                } else {
                    label.setBackground(Color.yellow.darker());
                }
            }
            if (isSelected) {
                label.setBackground(Color.cyan.darker());
            }

            //System.err.println("[" + row + ":" + column + "]");
            return label;

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonClearCustomerFilter;
    public final javax.swing.JButton jButtonRefresh = new javax.swing.JButton();
    public javax.swing.JButton jButtonUsernameAndFramedIPFilter;
    public javax.swing.JCheckBox jCheckBoxOnline;
    public javax.swing.JFormattedTextField jFormattedTextFieldDays;
    public javax.swing.JLabel jLabelCustomerFilter;
    public javax.swing.JLabel jLabelCustomerLocation;
    public javax.swing.JLabel jLabelCustomerName;
    public javax.swing.JLabel jLabelFilterLastDays1;
    public javax.swing.JLabel jLabelFilterLastDays2;
    public javax.swing.JLabel jLabelFramedIP;
    public javax.swing.JLabel jLabelLinkTime;
    public javax.swing.JLabel jLabelRadiusID;
    public javax.swing.JLabel jLabelRouter;
    public javax.swing.JLabel jLabelSessionID;
    public javax.swing.JLabel jLabelStartTIme;
    public javax.swing.JLabel jLabelStopTime;
    public javax.swing.JLabel jLabelUpdateTime;
    public javax.swing.JLabel jLabelUsername;
    public javax.swing.JLabel jLabelUsernameAndFramedIPFilter;
    public javax.swing.JPanel jPanelBottom;
    public javax.swing.JPanel jPanelCustomerFilter;
    public javax.swing.JPanel jPanelDetail;
    public javax.swing.JPanel jPanelFilter;
    public javax.swing.JPanel jPanelLastDays;
    public javax.swing.JPanel jPanelOnlyActiveFilter;
    public javax.swing.JPanel jPanelTableOnline;
    public javax.swing.JPanel jPanelUsernameAndFramedIPFilter;
    public javax.swing.JScrollPane jScrollPaneTableOnline;
    public javax.swing.JTable jTableOnline;
    public javax.swing.JTextField jTextFieldCustomerFilter;
    public javax.swing.JTextField jTextFieldCustomerLocation;
    public javax.swing.JTextField jTextFieldCustomerName;
    public javax.swing.JTextField jTextFieldFramedIP;
    public javax.swing.JTextField jTextFieldLinkTime;
    public javax.swing.JTextField jTextFieldRadiusID;
    public javax.swing.JTextField jTextFieldRouter;
    public javax.swing.JTextField jTextFieldSessionID;
    public javax.swing.JTextField jTextFieldStartTIme;
    public javax.swing.JTextField jTextFieldStopTime;
    public javax.swing.JTextField jTextFieldUpdateTime;
    public javax.swing.JTextField jTextFieldUsername;
    public javax.swing.JTextField jTextFieldUsernameAndFramedIPFilter;
    public javax.swing.JComboBox<String> jWhereOperation;
    // End of variables declaration//GEN-END:variables
}
