/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package net.ukrcom.onlinemanager;

import java.awt.event.ActionEvent;
import javax.swing.text.DefaultEditorKit;
import javax.swing.text.Document;
import javax.swing.text.JTextComponent;
import javax.swing.text.TextAction;

/**
 *
 * @author olden
 */
public class jCutCopyPaste extends Object {

    public final DefaultEditorKit.CutAction actionCut;
    public final DefaultEditorKit.CopyAction actionCopy;
    public final DefaultEditorKit.PasteAction actionPaste;
    public final SelectAllAction actionSelectAll;

    /**
     * Creates new form jCutCopyPaste
     */
    public jCutCopyPaste() {
        initComponents();
        this.actionCut = new DefaultEditorKit.CutAction();
        this.actionCopy = new DefaultEditorKit.CopyAction();
        this.actionPaste = new DefaultEditorKit.PasteAction();
        this.actionSelectAll = new SelectAllAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuItemPopupCut = new javax.swing.JMenuItem();
        jMenuItemPopupCopy = new javax.swing.JMenuItem();
        jMenuItemPopupPaste = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPopupSelectAll = new javax.swing.JMenuItem();

        jMenuItemPopupCut.setText("Cut");
        jMenuItemPopupCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPopupCutActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemPopupCut);

        jMenuItemPopupCopy.setText("Copy");
        jMenuItemPopupCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPopupCopyActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemPopupCopy);

        jMenuItemPopupPaste.setText("Paste");
        jMenuItemPopupPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPopupPasteActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemPopupPaste);
        jPopupMenu.add(jSeparator1);

        jMenuItemPopupSelectAll.setText("Select All");
        jMenuItemPopupSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPopupSelectAllActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemPopupSelectAll);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPopupCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPopupCutActionPerformed
        this.actionCut.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemPopupCutActionPerformed

    private void jMenuItemPopupCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPopupCopyActionPerformed
        this.actionCopy.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemPopupCopyActionPerformed

    private void jMenuItemPopupPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPopupPasteActionPerformed
        this.actionPaste.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemPopupPasteActionPerformed

    private void jMenuItemPopupSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPopupSelectAllActionPerformed
        this.actionSelectAll.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemPopupSelectAllActionPerformed

    static class SelectAllAction extends TextAction {

        /**
         * Create this action with the appropriate identifier.
         *
         * @param nm the name of the action, Action.NAME.
         * @param select whether to extend the selection when changing the caret
         * position.
         */
        SelectAllAction() {
            super(DefaultEditorKit.selectAllAction);
        }

        /**
         * The operation to perform when this action is triggered.
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            JTextComponent target = getTextComponent(e);
            if (target != null) {
                Document doc = target.getDocument();
                target.setCaretPosition(0);
                target.moveCaretPosition(doc.getLength());
            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItemPopupCopy;
    public javax.swing.JMenuItem jMenuItemPopupCut;
    public javax.swing.JMenuItem jMenuItemPopupPaste;
    private javax.swing.JMenuItem jMenuItemPopupSelectAll;
    public javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
