/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package net.ukrcom.onlinemanager;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Semaphore;
import javax.swing.SwingWorker;

/**
 *
 * @author olden
 */
public class JDialogDuplicateAutofix extends javax.swing.JDialog {

    private static final Semaphore semaphore = new Semaphore(3);

    /**
     * Creates new form JDialogDuplicateAutofix
     */
    public JDialogDuplicateAutofix(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.isCanceled = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelDuplicates = new javax.swing.JPanel();
        jLabelDuplicates = new javax.swing.JLabel();
        jProgressBarDuplicateData = new javax.swing.JProgressBar();
        jPanelCorrection = new javax.swing.JPanel();
        jLabelCorrection = new javax.swing.JLabel();
        jProgressBarDuplicateSessions = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jButtonRun = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Automatic correction of duplicates");
        setIconImage(null);
        setMinimumSize(getPreferredSize());
        setModal(true);
        setPreferredSize(new java.awt.Dimension(800, 200));
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        jPanelDuplicates.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelDuplicates.setLayout(new java.awt.GridLayout(2, 1));

        jLabelDuplicates.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDuplicates.setText("Duplicates");
        jPanelDuplicates.add(jLabelDuplicates);

        jProgressBarDuplicateData.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jProgressBarDuplicateData.setMaximumSize(new java.awt.Dimension(32767, 40));
        jProgressBarDuplicateData.setMinimumSize(getPreferredSize());
        jProgressBarDuplicateData.setPreferredSize(new java.awt.Dimension(800, 40));
        jPanelDuplicates.add(jProgressBarDuplicateData);

        getContentPane().add(jPanelDuplicates);

        jPanelCorrection.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelCorrection.setLayout(new java.awt.GridLayout(2, 1));

        jLabelCorrection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCorrection.setText("Correction");
        jPanelCorrection.add(jLabelCorrection);

        jProgressBarDuplicateSessions.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jProgressBarDuplicateSessions.setMaximumSize(new java.awt.Dimension(32767, 40));
        jProgressBarDuplicateSessions.setMinimumSize(getPreferredSize());
        jProgressBarDuplicateSessions.setPreferredSize(new java.awt.Dimension(800, 40));
        jPanelCorrection.add(jProgressBarDuplicateSessions);

        getContentPane().add(jPanelCorrection);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButtonRun.setText("Run");
        jButtonRun.setBorderPainted(false);
        jButtonRun.addActionListener(this::jButtonRunActionPerformed);
        jPanel1.add(jButtonRun);

        jButtonCancel.setText("Cancel");
        jButtonCancel.setBorderPainted(false);
        jButtonCancel.setEnabled(false);
        jButtonCancel.addActionListener(this::jButtonCancelActionPerformed);
        jPanel1.add(jButtonCancel);

        getContentPane().add(jPanel1);

        getAccessibleContext().setAccessibleName("Automatic fix of duplicates");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed
        try {
            this.isCanceled = false;
            jButtonCancel.setEnabled(!this.isCanceled);
            jButtonRun.setEnabled(this.isCanceled);

            ArrayList<Object> duplicateData = RestApiClient.getInstance().getDuplicateData();
            duplicateRunAction = new DuplicateRunAction(duplicateData);
            duplicateRunAction.execute();

        } catch (IOException | ClassNotFoundException | InterruptedException ex) {
            System.getLogger(JDialogDuplicateAutofix.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButtonRunActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.isCanceled = true;
        duplicateRunAction.cancel(this.isCanceled);
        jButtonCancel.setEnabled(!this.isCanceled);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JLabel jLabelCorrection;
    private javax.swing.JLabel jLabelDuplicates;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCorrection;
    private javax.swing.JPanel jPanelDuplicates;
    private javax.swing.JProgressBar jProgressBarDuplicateData;
    private javax.swing.JProgressBar jProgressBarDuplicateSessions;
    // End of variables declaration//GEN-END:variables

    boolean isCanceled;
    private DuplicateRunAction duplicateRunAction;

    private record DuplicateData(
            int dataCounter,
            String username,
            int count) {

    }

    private record SessionData(
            int dataCounter,
            int sessionsCounter,
            long radacctid,
            String username,
            String framedipaddress,
            String acctstarttime,
            String acctupdatetime) {

    }

    private class DuplicateRunAction extends SwingWorker<Void, SessionData> {

        private int duplicateDataCounter, duplicateSessionsCounter;
        ArrayList<Object> duplicateData, duplicateSessions, stopTimeCandidate;

        private DuplicateRunAction(ArrayList<Object> duplicateData) {
            duplicateDataCounter = 0;
            duplicateSessionsCounter = 0;
            this.duplicateData = duplicateData;
            jProgressBarDuplicateData.setMaximum(duplicateData.size());
            jProgressBarDuplicateData.setValue(duplicateDataCounter);
        }

        @Override
        protected Void doInBackground() throws Exception {

            jProgressBarDuplicateData.setValue(duplicateDataCounter);
            for (Object objectData : duplicateData) {

                DuplicateData dataDuplicate = new DuplicateData(
                        duplicateDataCounter,
                        (String) ((Object[]) objectData)[0],
                        Integer.parseInt((String) ((Object[]) objectData)[1])
                );

                duplicateSessions = RestApiClient.getInstance().getDuplicateSessions(dataDuplicate.username);
                duplicateSessionsCounter = 0;
                jProgressBarDuplicateSessions.setMaximum(duplicateSessions.size());
                jProgressBarDuplicateSessions.setValue(duplicateSessionsCounter);

                for (Object objectSessions : duplicateSessions) {
                    SessionData dataSession = new SessionData(
                            dataDuplicate.dataCounter,
                            duplicateSessionsCounter,
                            Long.parseLong((String) ((Object[]) objectSessions)[0]),
                            (String) ((Object[]) objectData)[0],
                            (String) ((Object[]) objectSessions)[1],
                            (String) ((Object[]) objectSessions)[2],
                            (String) ((Object[]) objectSessions)[3]
                    );
                    semaphore.acquire();

                    jProgressBarDuplicateData.setToolTipText(dataSession.username);
                    jLabelDuplicates.setText("Duplicates: " + dataSession.username);
                    jLabelDuplicates.repaint();
                    publish(dataSession);
                    jProgressBarDuplicateSessions.setValue(++duplicateSessionsCounter);
                }

                jProgressBarDuplicateData.setValue(++duplicateDataCounter);
            }
            return null;
        }

        @Override
        public void process(List<SessionData> data) {
            try {
                if (isCancelled()) {
                    return;
                }

                try {
                    stopTimeCandidate = RestApiClient.getInstance().getAcctStopTimeCandidate(
                            data.get(data.size() - 1).acctstarttime,
                            data.get(data.size() - 1).username,
                            data.get(data.size() - 1).framedipaddress
                    );

                    for (Object objectStopTimeCandidate : stopTimeCandidate) {
                        String acctstoptime = (String) ((Object[]) objectStopTimeCandidate)[1];

                        jProgressBarDuplicateSessions.setToolTipText(acctstoptime);
                        jLabelCorrection.setText("Correction: " + jLabelDuplicates.getText() + " – " + data.get(data.size() - 1).acctstarttime + " – " + acctstoptime);
                        jLabelCorrection.repaint();

                        System.err.println("DuplicateSessionsAction.process: "
                                + data.get(data.size() - 1).dataCounter + " "
                                + data.get(data.size() - 1).sessionsCounter + " "
                                + data.get(data.size() - 1).radacctid + " "
                                + data.get(data.size() - 1).username + " "
                                + data.get(data.size() - 1).framedipaddress + " "
                                + data.get(data.size() - 1).acctstarttime + " "
                                + data.get(data.size() - 1).acctupdatetime + " "
                                + acctstoptime
                        );

                        RestApiClient.getInstance().correctionAcctStopTime(
                                data.get(data.size() - 1).radacctid,
                                acctstoptime
                        );

                    }
                } catch (IOException | ClassNotFoundException | InterruptedException ex) {
                    System.getLogger(JDialogDuplicateAutofix.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            } finally {
                semaphore.release();
            }
        }

        @Override
        protected void done() {
            jButtonCancel.setText("Close");
        }

    }

}
