/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.ukrcom.onlinemanager;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.IOException;
import java.io.StringReader;
import java.sql.SQLException;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author olden
 */
public class JFrameDuplicateCheck extends javax.swing.JFrame {

    /**
     * Creates new form JFrameDuplicateCheck
     *
     */
    public JFrameDuplicateCheck() {
        initComponents();
        this.jTableDuplicateSessionsLoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCutCopyPaste = new net.ukrcom.onlinemanager.jCutCopyPaste();
        jPanelDuplicateSessions = new javax.swing.JPanel();
        jLabelDuplicateSessions = new javax.swing.JLabel();
        jScrollPaneDuplicateSessions = new javax.swing.JScrollPane();
        jTableDuplicateSessions = new javax.swing.JTable();
        jPanelDetailedList = new javax.swing.JPanel();
        jPanelSessionsList = new javax.swing.JPanel();
        jLabelUsernameDetail = new javax.swing.JLabel();
        jScrollPaneUsernameDetail = new javax.swing.JScrollPane();
        jTableUsernameDetail = new javax.swing.JTable();
        jPanelSessionAnalyzer = new javax.swing.JPanel();
        jLabelSessionFoundByUsername = new javax.swing.JLabel();
        jScrollPaneSessionFoundByUsername = new javax.swing.JScrollPane();
        jTableSessionFoundByUsername = new javax.swing.JTable();
        jLabelRequestCorrection = new javax.swing.JLabel();
        jScrollPaneRequestCorrection = new javax.swing.JScrollPane();
        jTextPaneRequestCorrection = new javax.swing.JTextPane();
        jButtonRequestCorrection = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemClose = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemCut = new javax.swing.JMenuItem();
        jMenuItemCopy = new javax.swing.JMenuItem();
        jMenuItemPaste = new javax.swing.JMenuItem();
        jSeparator = new javax.swing.JPopupMenu.Separator();
        jMenuItemSelectAll = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Duplicate Check");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frameDuplicateCheck"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanelDuplicateSessions.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        jPanelDuplicateSessions.setLayout(new java.awt.GridBagLayout());

        jLabelDuplicateSessions.setText("List of duplicate sessions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanelDuplicateSessions.add(jLabelDuplicateSessions, gridBagConstraints);

        jTableDuplicateSessions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username", "count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDuplicateSessions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableDuplicateSessions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableDuplicateSessions.setShowHorizontalLines(true);
        jTableDuplicateSessions.setDefaultRenderer(String.class, new DuplicateSessionsImageTextCellRenderer());
        jTableDuplicateSessions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDuplicateSessionsMouseClicked(evt);
            }
        });
        jTableDuplicateSessions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableDuplicateSessionsKeyReleased(evt);
            }
        });
        jScrollPaneDuplicateSessions.setViewportView(jTableDuplicateSessions);
        jTableDuplicateSessions.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelDuplicateSessions.add(jScrollPaneDuplicateSessions, gridBagConstraints);

        getContentPane().add(jPanelDuplicateSessions);

        jPanelDetailedList.setLayout(new java.awt.GridBagLayout());

        jPanelSessionsList.setLayout(new java.awt.GridBagLayout());

        jLabelUsernameDetail.setText("Detail by username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanelSessionsList.add(jLabelUsernameDetail, gridBagConstraints);

        jTableUsernameDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "radacctid", "framedipaddress", "acctstarttime", "acctupdatetime"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsernameDetail.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableUsernameDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsernameDetailMouseClicked(evt);
            }
        });
        jTableUsernameDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableUsernameDetailKeyReleased(evt);
            }
        });
        jScrollPaneUsernameDetail.setViewportView(jTableUsernameDetail);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelSessionsList.add(jScrollPaneUsernameDetail, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 4.0;
        gridBagConstraints.weighty = 1.0;
        jPanelDetailedList.add(jPanelSessionsList, gridBagConstraints);

        jPanelSessionAnalyzer.setLayout(new java.awt.GridBagLayout());

        jLabelSessionFoundByUsername.setText("End of session found by username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        jPanelSessionAnalyzer.add(jLabelSessionFoundByUsername, gridBagConstraints);

        jTableSessionFoundByUsername.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "acctstarttime", "acctstoptime"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSessionFoundByUsername.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneSessionFoundByUsername.setViewportView(jTableSessionFoundByUsername);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelSessionAnalyzer.add(jScrollPaneSessionFoundByUsername, gridBagConstraints);

        jLabelRequestCorrection.setText("Request for correction");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        jPanelSessionAnalyzer.add(jLabelRequestCorrection, gridBagConstraints);

        jTextPaneRequestCorrection.setEditable(false);
        jTextPaneRequestCorrection.setContentType("text/html"); // NOI18N
        jScrollPaneRequestCorrection.setViewportView(jTextPaneRequestCorrection);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 5.0;
        jPanelSessionAnalyzer.add(jScrollPaneRequestCorrection, gridBagConstraints);

        jButtonRequestCorrection.setText("Do it");
        jButtonRequestCorrection.setEnabled(false);
        jButtonRequestCorrection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestCorrectionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        jPanelSessionAnalyzer.add(jButtonRequestCorrection, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        jPanelDetailedList.add(jPanelSessionAnalyzer, gridBagConstraints);

        getContentPane().add(jPanelDetailedList);

        jMenuFile.setText("File");

        jMenuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemClose.setText("Close");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemClose);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCut.setText("Cut");
        jMenuItemCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCutActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemCut);

        jMenuItemCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCopy.setText("Copy");
        jMenuItemCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCopyActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemCopy);

        jMenuItemPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemPaste.setText("Paste");
        jMenuItemPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPasteActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemPaste);
        jMenuEdit.add(jSeparator);

        jMenuItemSelectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSelectAll.setText("Select All");
        jMenuItemSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSelectAllActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemSelectAll);

        jMenuBar1.add(jMenuEdit);

        jMenu1.setText("Data");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Refresh");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1034, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    private void jMenuItemCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCutActionPerformed
        this.jCutCopyPaste.actionCut.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCutActionPerformed

    private void jMenuItemCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopyActionPerformed
        this.jCutCopyPaste.actionCopy.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCopyActionPerformed

    private void jMenuItemPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPasteActionPerformed
        this.jCutCopyPaste.actionPaste.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemPasteActionPerformed

    private void jMenuItemSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSelectAllActionPerformed
        this.jCutCopyPaste.actionSelectAll.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemSelectAllActionPerformed

    private void jTableDuplicateSessionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDuplicateSessionsMouseClicked
        this.jTableDuplicateSessionsSelectRow(
                this.jTableDuplicateSessions.getSelectedRow()
        );
    }//GEN-LAST:event_jTableDuplicateSessionsMouseClicked

    private void jTableDuplicateSessionsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableDuplicateSessionsKeyReleased
        this.jTableDuplicateSessionsSelectRow(
                this.jTableDuplicateSessions.getSelectedRow()
        );
    }//GEN-LAST:event_jTableDuplicateSessionsKeyReleased

    private void jTableUsernameDetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableUsernameDetailKeyReleased
        this.jTableUsernameDetailSelectRow(
                this.jTableUsernameDetail.getSelectedRow()
        );
    }//GEN-LAST:event_jTableUsernameDetailKeyReleased

    private void jTableUsernameDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsernameDetailMouseClicked
        this.jTableUsernameDetailSelectRow(
                this.jTableUsernameDetail.getSelectedRow()
        );
    }//GEN-LAST:event_jTableUsernameDetailMouseClicked

    private void jButtonRequestCorrectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestCorrectionActionPerformed
        Html2Text h2t = new Html2Text();
        try {
            h2t.parse(new StringReader(this.jTextPaneRequestCorrection.getText()));
        } catch (IOException ex) {
            Logger.getLogger(JFrameDuplicateCheck.class.getName()).log(Level.SEVERE, null, ex);
        }

        String SQL = h2t.getText().replaceAll("\\\n", " ").replaceAll("\\s+", " ").trim();

        if (!SQL.isBlank()) {
            try {
                radiusData radiusData = new radiusData()
                        .correctionAcctStopTime(
                                Long.valueOf(this.currentRadAcctID),
                                this.candidateAcctStopTime
                        ).closeConnections();
            } catch (SQLException ex) {
                Logger.getLogger(JFrameDuplicateCheck.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonRequestCorrectionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.jTableDuplicateSessionsLoadData();

        DefaultTableModel model;

        model = (DefaultTableModel) this.jTableUsernameDetail.getModel();
        model.setRowCount(0);

        model = (DefaultTableModel) this.jTableSessionFoundByUsername.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTableDuplicateSessionsLoadData() {
        try {
            radiusData radiusData = new radiusData()
                    .getDuplicateData(
                            (DefaultTableModel) this.jTableDuplicateSessions.getModel()
                    ).closeConnections();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameDuplicateCheck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jTableDuplicateSessionsSelectRow(int selectedRow) {

        if (selectedRow >= 0
                && this.currentUsername != null
                && this.currentUsername == (String) this.jTableDuplicateSessions.getValueAt(selectedRow, 0)) {
            return;
        }
        if (this.jTableDuplicateSessions.getRowCount() < 0) {
            return;
        }

//        System.err.println(this.jTableDuplicateSessions.getRowCount() + " " + selectedRow);
        this.currentUsername = (String) this.jTableDuplicateSessions.getValueAt(selectedRow, 0);

        DefaultTableModel model;

        model = (DefaultTableModel) this.jTableUsernameDetail.getModel();
        model.setRowCount(0);

        model = (DefaultTableModel) this.jTableSessionFoundByUsername.getModel();
        model.setRowCount(0);

        this.jTextPaneRequestCorrection.setText("");
        this.jButtonRequestCorrection.setEnabled(false);

        this.currentRadAcctID = null;
        this.currentFramedIPAddress = null;
        this.currentAcctStartTime = null;
        this.candidateAcctStopTime = null;

        try {
            radiusData radiusData = new radiusData()
                    .getDuplicateSessions(
                            (DefaultTableModel) jTableUsernameDetail.getModel(),
                            this.currentUsername
                    ).closeConnections();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameDuplicateCheck.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jTableUsernameDetailSelectRow(int selectedRow) {

        if (selectedRow >= 0
                && this.currentRadAcctID != null
                && this.currentRadAcctID.compareTo(Long.valueOf(jTableUsernameDetail.getValueAt(selectedRow, 0).toString())) == 0) {
            return;
        }

        this.currentRadAcctID = Long.valueOf(this.jTableUsernameDetail.getValueAt(selectedRow, 0).toString());
        this.currentFramedIPAddress = this.jTableUsernameDetail.getValueAt(selectedRow, 1).toString();
        this.currentAcctStartTime = this.jTableUsernameDetail.getValueAt(selectedRow, 2).toString();

        try {
            radiusData radiusData = new radiusData()
                    .getAcctStopTimeCandidate(
                            (DefaultTableModel) this.jTableSessionFoundByUsername.getModel(),
                            this.currentAcctStartTime,
                            this.currentUsername,
                            this.currentFramedIPAddress
                    ).closeConnections();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameDuplicateCheck.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (jTableSessionFoundByUsername.getRowCount() > 0) {
            this.candidateAcctStopTime = this.jTableSessionFoundByUsername.getValueAt(0, 1).toString();
        } else {
            this.candidateAcctStopTime = null;
        }

        if (this.candidateAcctStopTime != null) {
            this.jTextPaneRequestCorrection.setText("<b>UPDATE</b> <i>radacct</i> <b>SET</b> <i>acctstoptime</i>='" + this.candidateAcctStopTime + "' <b>WHERE</b> <i>radacctid</i>=" + this.currentRadAcctID);
            this.jButtonRequestCorrection.setEnabled(true);
        } else {
            this.jTextPaneRequestCorrection.setText("");
            this.jButtonRequestCorrection.setEnabled(false);
        }

    }

    class DuplicateSessionsImageTextCellRenderer extends DefaultTableCellRenderer {

        Color backgroundColor = getBackground();

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            String text = (String) value;
            JLabel label = (JLabel) super.getTableCellRendererComponent(table, text, isSelected, hasFocus, row, column);
//            System.err.println(column + " " + text);
            switch (column) {
                case 0 -> {
                    label.setHorizontalAlignment(JLabel.LEFT);
                    Font font = label.getFont().deriveFont(
                            Collections.singletonMap(TextAttribute.WEIGHT, TextAttribute.WEIGHT_ULTRABOLD)
                    );
                    label.setFont(font);
                }
                case 1 -> {
                    label.setHorizontalAlignment(JLabel.CENTER);
                }
                default ->
                    label.setHorizontalAlignment(JLabel.LEFT);
            }
            return label;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRequestCorrection;
    private net.ukrcom.onlinemanager.jCutCopyPaste jCutCopyPaste;
    private javax.swing.JLabel jLabelDuplicateSessions;
    private javax.swing.JLabel jLabelRequestCorrection;
    private javax.swing.JLabel jLabelSessionFoundByUsername;
    private javax.swing.JLabel jLabelUsernameDetail;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemCopy;
    private javax.swing.JMenuItem jMenuItemCut;
    private javax.swing.JMenuItem jMenuItemPaste;
    private javax.swing.JMenuItem jMenuItemSelectAll;
    private javax.swing.JPanel jPanelDetailedList;
    private javax.swing.JPanel jPanelDuplicateSessions;
    private javax.swing.JPanel jPanelSessionAnalyzer;
    private javax.swing.JPanel jPanelSessionsList;
    private javax.swing.JScrollPane jScrollPaneDuplicateSessions;
    private javax.swing.JScrollPane jScrollPaneRequestCorrection;
    private javax.swing.JScrollPane jScrollPaneSessionFoundByUsername;
    private javax.swing.JScrollPane jScrollPaneUsernameDetail;
    private javax.swing.JPopupMenu.Separator jSeparator;
    private javax.swing.JTable jTableDuplicateSessions;
    private javax.swing.JTable jTableSessionFoundByUsername;
    private javax.swing.JTable jTableUsernameDetail;
    private javax.swing.JTextPane jTextPaneRequestCorrection;
    // End of variables declaration//GEN-END:variables

    private String currentUsername;
    private Long currentRadAcctID;
    private String currentFramedIPAddress;
    private String currentAcctStartTime;
    private String candidateAcctStopTime;
}
