/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.ukrcom.onlinemanager;

import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JFrame;
import org.apache.commons.lang3.SystemUtils;

/**
 *
 * @author olden
 */
public final class jMainFrame extends javax.swing.JFrame {

    protected jCutCopyPaste jCutCopyPaste;

    /**
     * Creates new form jMainFrame
     */
    public jMainFrame() {
        this.mainPanelVisible = true;
        this.jCutCopyPaste = new jCutCopyPaste();
        initComponents();
        VersionChecker.checkForUpdates(this);
        this.timer = new Timer(this);
        checkStateAutoRefresh();
        this.gridOnlinePanel.getRootPane().setDefaultButton(this.gridOnlinePanel.jButtonRefresh);
        updateRowCountInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        gridOnlinePanel = new net.ukrcom.onlinemanager.gridOnline();
        jMainMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemEditCut = new javax.swing.JMenuItem();
        jMenuItemEditCopy = new javax.swing.JMenuItem();
        jMenuItemEditPaste = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSelectAll = new javax.swing.JMenuItem();
        jMenuRefresh = new javax.swing.JMenu();
        jMenuItemResetAndRefresh = new javax.swing.JMenuItem();
        jCheckBoxMenuItemAutoRefresh = new javax.swing.JCheckBoxMenuItem();
        jMenuWindow = new javax.swing.JMenu();
        jMenuItemMainPanel = new javax.swing.JMenuItem();
        jMenuItemDuplicateCheck = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSetup = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Manager");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/onlinemanager."+( SystemUtils.IS_OS_WINDOWS ? "ico" : "png"))));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().add(gridOnlinePanel, java.awt.BorderLayout.CENTER);

        jMenuFile.setText("File");

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMainMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemEditCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEditCut.setText("Cut");
        jMenuItemEditCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditCutActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemEditCut);

        jMenuItemEditCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEditCopy.setText("Copy");
        jMenuItemEditCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditCopyActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemEditCopy);

        jMenuItemEditPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEditPaste.setText("Paste");
        jMenuItemEditPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditPasteActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemEditPaste);
        jMenuEdit.add(jSeparator1);

        jMenuItemSelectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSelectAll.setText("Select All");
        jMenuItemSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSelectAllActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemSelectAll);

        jMainMenuBar.add(jMenuEdit);

        jMenuRefresh.setText("Data");

        jMenuItemResetAndRefresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemResetAndRefresh.setText("Reset and Refresh");
        jMenuItemResetAndRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResetAndRefreshActionPerformed(evt);
            }
        });
        jMenuRefresh.add(jMenuItemResetAndRefresh);

        jCheckBoxMenuItemAutoRefresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItemAutoRefresh.setSelected(true);
        jCheckBoxMenuItemAutoRefresh.setText("Auto Refresh");
        jCheckBoxMenuItemAutoRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemAutoRefreshActionPerformed(evt);
            }
        });
        jMenuRefresh.add(jCheckBoxMenuItemAutoRefresh);

        jMainMenuBar.add(jMenuRefresh);

        jMenuWindow.setText("Window");

        jMenuItemMainPanel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemMainPanel.setText("Main panel");
        jMenuItemMainPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMainPanelActionPerformed(evt);
            }
        });
        jMenuWindow.add(jMenuItemMainPanel);

        jMenuItemDuplicateCheck.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemDuplicateCheck.setText("Duplicate check");
        jMenuItemDuplicateCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDuplicateCheckActionPerformed(evt);
            }
        });
        jMenuWindow.add(jMenuItemDuplicateCheck);
        jMenuWindow.add(jSeparator3);

        jMenuItemSetup.setText("Setup");
        jMenuItemSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSetupActionPerformed(evt);
            }
        });
        jMenuWindow.add(jMenuItemSetup);

        jMainMenuBar.add(jMenuWindow);

        setJMenuBar(jMainMenuBar);

        setBounds(0, 0, 1210, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void Exit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit
        try {
            RadiusData.getInstance().closeConnections();
        } catch (SQLException ignored) {
        }
        System.exit(0);
    }//GEN-LAST:event_Exit

    private void jMenuItemEditCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditCutActionPerformed
        this.jCutCopyPaste.actionCut.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemEditCutActionPerformed

    private void jMenuItemEditCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditCopyActionPerformed
        this.jCutCopyPaste.actionCopy.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemEditCopyActionPerformed

    private void jMenuItemEditPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditPasteActionPerformed
        this.jCutCopyPaste.actionPaste.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemEditPasteActionPerformed

    private void jMenuItemSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSelectAllActionPerformed
        this.jCutCopyPaste.actionSelectAll.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemSelectAllActionPerformed

    private void jMenuItemResetAndRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResetAndRefreshActionPerformed
        fullRefresh();
    }//GEN-LAST:event_jMenuItemResetAndRefreshActionPerformed

    private void jMenuItemMainPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMainPanelActionPerformed
        if (this.mainPanelVisible) {
            this.getContentPane().removeAll();
            this.getContentPane().revalidate();
            this.repaint();
        } else {
            getContentPane().add(this.gridOnlinePanel, java.awt.BorderLayout.CENTER);
            this.getContentPane().revalidate();
            this.repaint();
        }
        this.mainPanelVisible = !this.mainPanelVisible;
    }//GEN-LAST:event_jMenuItemMainPanelActionPerformed

    private void jMenuItemDuplicateCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDuplicateCheckActionPerformed
        if (this.duplicateCheck == null) {
            this.duplicateCheck = new JFrameDuplicateCheck();
        }

        if (this.duplicateCheck.isVisible()) {
            this.duplicateCheck.setVisible(false);
        } else {
            this.duplicateCheck.setVisible(true);
        }
        this.duplicateCheck.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.duplicateCheck.setExtendedState(this.duplicateCheck.getExtendedState() | JFrame.MAXIMIZED_HORIZ);
        //this.duplicateCheck.setExtendedState(this.duplicateCheck.getExtendedState() | JFrame.MAXIMIZED_BOTH );
    }//GEN-LAST:event_jMenuItemDuplicateCheckActionPerformed

    private void jMenuItemSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSetupActionPerformed

        if (this.setup == null) {
            this.setup = new JSetup(this);
        }
        this.setup.setLocationRelativeTo(this);
        this.setup.setVisible(true);
    }//GEN-LAST:event_jMenuItemSetupActionPerformed

    private void jCheckBoxMenuItemAutoRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemAutoRefreshActionPerformed
        checkStateAutoRefresh();
    }//GEN-LAST:event_jCheckBoxMenuItemAutoRefreshActionPerformed

    private void checkStateAutoRefresh() {
        if (this.jCheckBoxMenuItemAutoRefresh.isSelected()) {
            this.timer.start();
        } else {
            this.jCheckBoxMenuItemAutoRefresh.setText("Auto Refresh");
            this.timer.stop();
        }
    }

    public void fullRefresh() {
        this.gridOnlinePanel.jButtonRefresh.setEnabled(false);

        this.gridOnlinePanel.jFormattedTextFieldDays.setText("1");
        this.gridOnlinePanel.jTextFieldUsernameAndFramedIPFilter.setText("");
        this.gridOnlinePanel.jTextFieldCustomerFilter.setText("");
        this.gridOnlinePanel.loadData();
        this.gridOnlinePanel.jLabelCustomerFilter.requestFocus();
        updateRowCountInfo();

        this.gridOnlinePanel.jButtonRefresh.setEnabled(true);
    }

    public void simpleRefresh() {
        this.gridOnlinePanel.jButtonRefresh.setEnabled(false);

        this.gridOnlinePanel.loadData();
        updateRowCountInfo();

        this.gridOnlinePanel.jButtonRefresh.setEnabled(true);
    }

    public void updateRowCountInfo() {
        this.gridOnlinePanel.updateRowCountInfo();
    }

    @Override
    public void dispose() {
        if (timer != null) {
            timer.stop();
        }
        try {
            RadiusData.getInstance().closeConnections();
        } catch (SQLException ignored) {
        }
        super.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected net.ukrcom.onlinemanager.gridOnline gridOnlinePanel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    protected javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemAutoRefresh;
    private javax.swing.JMenuBar jMainMenuBar;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemDuplicateCheck;
    private javax.swing.JMenuItem jMenuItemEditCopy;
    private javax.swing.JMenuItem jMenuItemEditCut;
    private javax.swing.JMenuItem jMenuItemEditPaste;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemMainPanel;
    private javax.swing.JMenuItem jMenuItemResetAndRefresh;
    private javax.swing.JMenuItem jMenuItemSelectAll;
    private javax.swing.JMenuItem jMenuItemSetup;
    private javax.swing.JMenu jMenuRefresh;
    private javax.swing.JMenu jMenuWindow;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

    private boolean mainPanelVisible;
    private JFrame duplicateCheck;
    private JSetup setup;
    private final Timer timer;
}
