@startuml

class Html2Text {
	{field} ~s : StringBuffer
	{method} +getText () : String
	{method} +handleText ( param[C1 : char[] , paramint2 : int ) : void
	{method} +parse ( paramReader1 : Reader ) : void
}


class JFrameDuplicateCheck {
	{field} -candidateAcctStopTime : String
	{field} -currentAcctStartTime : String
	{field} -currentFramedIPAddress : String
	{field} -currentRadAcctID : Long
	{field} -currentUsername : String
	{field} -jButtonRequestCorrection : JButton
	{field} -jLabelDuplicateSessions : JLabel
	{field} -jLabelRequestCorrection : JLabel
	{field} -jLabelSessionFoundByUsername : JLabel
	{field} -jLabelUsernameDetail : JLabel
	{field} -jMenu1 : JMenu
	{field} -jMenuBar1 : JMenuBar
	{field} -jMenuEdit : JMenu
	{field} -jMenuFile : JMenu
	{field} -jMenuItem1 : JMenuItem
	{field} -jMenuItemClose : JMenuItem
	{field} -jMenuItemCopy : JMenuItem
	{field} -jMenuItemCut : JMenuItem
	{field} -jMenuItemPaste : JMenuItem
	{field} -jMenuItemSelectAll : JMenuItem
	{field} -jPanelDetailedList : JPanel
	{field} -jPanelDuplicateSessions : JPanel
	{field} -jPanelSessionAnalyzer : JPanel
	{field} -jPanelSessionsList : JPanel
	{field} -jScrollPaneDuplicateSessions : JScrollPane
	{field} -jScrollPaneRequestCorrection : JScrollPane
	{field} -jScrollPaneSessionFoundByUsername : JScrollPane
	{field} -jScrollPaneUsernameDetail : JScrollPane
	{field} -jSeparator : Separator
	{field} -jTableDuplicateSessions : JTable
	{field} -jTableSessionFoundByUsername : JTable
	{field} -jTableUsernameDetail : JTable
	{field} -jTextPaneRequestCorrection : JTextPane
	{method} -initComponents () : void
	{method} -jButtonRequestCorrectionActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItem1ActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemCloseActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemCopyActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemCutActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemPasteActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemSelectAllActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jTableDuplicateSessionsKeyReleased ( paramKeyEvent1 : KeyEvent ) : void
	{method} -jTableDuplicateSessionsLoadData () : void
	{method} -jTableDuplicateSessionsMouseClicked ( paramMouseEvent1 : MouseEvent ) : void
	{method} -jTableDuplicateSessionsSelectRow ( paramint1 : int ) : void
	{method} -jTableUsernameDetailKeyReleased ( paramKeyEvent1 : KeyEvent ) : void
	{method} -jTableUsernameDetailMouseClicked ( paramMouseEvent1 : MouseEvent ) : void
	{method} -jTableUsernameDetailSelectRow ( paramint1 : int ) : void
}


class JSetup {
	{field} -jButtonCancel : JButton
	{field} -jButtonDatabaseName : JButton
	{field} -jButtonOk : JButton
	{field} -jButtonPassword : JButton
	{field} -jButtonRESTPassword : JButton
	{field} -jButtonRESTServerName : JButton
	{field} -jButtonRESTUsername : JButton
	{field} -jButtonServerName : JButton
	{field} -jButtonUsername : JButton
	{field} -jLabelDatabase : JLabel
	{field} -jLabelDatabaseName : JLabel
	{field} -jLabelPassword : JLabel
	{field} -jLabelREST : JLabel
	{field} -jLabelRESTPassword : JLabel
	{field} -jLabelRESTServerName : JLabel
	{field} -jLabelRESTUsername : JLabel
	{field} -jLabelServerName : JLabel
	{field} -jLabelUsername : JLabel
	{field} -jPanelDatabaseConfig : JPanel
	{field} -jPanelOkCancel : JPanel
	{field} -jPanelRESTConfig : JPanel
	{field} -jPasswordFieldPassword : JPasswordField
	{field} -jPasswordFieldRESTPassword : JPasswordField
	{field} -jSeparator1 : JSeparator
	{field} -jTextFieldDatabaseName : JTextField
	{field} -jTextFieldRESTServerName : JTextField
	{field} -jTextFieldRESTUsername : JTextField
	{field} -jTextFieldServerName : JTextField
	{field} -jTextFieldUsername : JTextField
	{field} -owner : JFrame
	{field} -setup : JFrame
	{method} -formWindowActivated ( paramWindowEvent1 : WindowEvent ) : void
	{method} -initComponents () : void
	{method} -jButtonCancelActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonDatabaseNameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonOkActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonPasswordActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonRESTPasswordActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonRESTServerNameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonRESTUsernameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonServerNameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonUsernameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -loadConfig () : void
}


class Onlinemanager {
	{method}  {static} +main ( paramString;1 : String[] ) : void
}


class RestApiClient {
	{field} -baseUrl : String
	{field} -http : HttpClient
	{field} -mapper : ObjectMapper
	{field} -token : String
	{method} -buildRequest ( paramString1 : String , paramString2 : String ) : JsonNode
	{method} +correctionAcctStopTime ( paramLong1 : Long , paramString2 : String ) : RestApiClient
	{method}  {static} -encode ( paramString1 : String ) : String
	{method} +getAcctStopTimeCandidate ( paramDefaultTableModel1 : DefaultTableModel , paramString2 : String , paramString3 : String , paramString4 : String ) : RestApiClient
	{method} +getData ( paramDefaultTableModel1 : DefaultTableModel , paramint2 : int , paramboolean3 : boolean , paramint4 : int , paramString5 : String , paramString6 : String ) : RestApiClient
	{method} +getDuplicateData ( paramDefaultTableModel1 : DefaultTableModel ) : RestApiClient
	{method} +getDuplicateSessions ( paramDefaultTableModel1 : DefaultTableModel , paramString2 : String ) : RestApiClient
	{method} +login ( paramString1 : String , paramString2 : String ) : boolean
	{method} +logout () : void
	{method} -post ( paramString1 : String , paramString2 : String ) : JsonNode
	{method}  {static} -text ( paramJsonNode1 : JsonNode , paramString2 : String ) : String
}


class Timer {
	{field} -timer : Timer
	{method} +start () : void
	{method} +stop () : void
}


class VersionChecker {
	{field} {static} -GITHUB_API_URL : String
	{field} {static} -RELEASES_URL : String
	{method}  {static} +checkForUpdates ( paramJFrame1 : JFrame ) : void
	{method}  {static} -extractTagFromJson ( paramString1 : String ) : String
	{method}  {static} +getCurrentVersion () : String
	{method}  {static} -isNewerVersion ( paramString1 : String , paramString2 : String ) : boolean
	{method}  {static} -openInBrowser ( paramString1 : String ) : void
}


class gridOnline {
	{field} +jButtonClearCustomerFilter : JButton
	{field} +jButtonRefresh : JButton
	{field} +jButtonUsernameAndFramedIPFilter : JButton
	{field} +jCheckBoxOnline : JCheckBox
	{field} +jFormattedTextFieldDays : JFormattedTextField
	{field} +jLabelCustomerFilter : JLabel
	{field} +jLabelCustomerLocation : JLabel
	{field} +jLabelCustomerName : JLabel
	{field} +jLabelFilterLastDays1 : JLabel
	{field} +jLabelFilterLastDays2 : JLabel
	{field} +jLabelFramedIP : JLabel
	{field} +jLabelLinkTime : JLabel
	{field} +jLabelRadiusID : JLabel
	{field} +jLabelRouter : JLabel
	{field} +jLabelSessionID : JLabel
	{field} +jLabelStartTIme : JLabel
	{field} +jLabelStopTime : JLabel
	{field} +jLabelTableOnlineRowCount : JLabel
	{field} +jLabelUpdateTime : JLabel
	{field} +jLabelUsername : JLabel
	{field} +jLabelUsernameAndFramedIPFilter : JLabel
	{field} +jPanelBottom : JPanel
	{field} +jPanelCustomerFilter : JPanel
	{field} +jPanelDetail : JPanel
	{field} +jPanelFilter : JPanel
	{field} +jPanelLastDays : JPanel
	{field} +jPanelOnlyActiveFilter : JPanel
	{field} +jPanelTableOnline : JPanel
	{field} +jPanelUsernameAndFramedIPFilter : JPanel
	{field} +jScrollPaneTableOnline : JScrollPane
	{field} +jTableOnline : JTable
	{field} +jTextFieldCustomerFilter : JTextField
	{field} +jTextFieldCustomerLocation : JTextField
	{field} +jTextFieldCustomerName : JTextField
	{field} +jTextFieldFramedIP : JTextField
	{field} +jTextFieldLinkTime : JTextField
	{field} +jTextFieldRadiusID : JTextField
	{field} +jTextFieldRouter : JTextField
	{field} +jTextFieldSessionID : JTextField
	{field} +jTextFieldStartTIme : JTextField
	{field} +jTextFieldStopTime : JTextField
	{field} +jTextFieldUpdateTime : JTextField
	{field} +jTextFieldUsername : JTextField
	{field} +jTextFieldUsernameAndFramedIPFilter : JTextField
	{field} +jWhereOperation : JComboBox
	{method} -initComponents () : void
	{method} -jButtonClearCustomerFilterActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonRefreshActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonUsernameAndFramedIPFilterActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jCheckBoxOnlineActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jTableOnlineKeyReleased ( paramKeyEvent1 : KeyEvent ) : void
	{method} -jTableOnlineMouseClicked ( paramMouseEvent1 : MouseEvent ) : void
	{method} +jTableOnlineSelectRow ( paramint1 : int ) : void
	{method} +loadData () : void
	{method} +showCell ( paramint1 : int , paramint2 : int ) : int
	{method} +updateRowCountInfo () : void
}


class jConfig {
	{field} +databaseName : String
	{field} +password : String
	{field} +restApiUrl : String
	{field} +restpassword : String
	{field} +restserverName : String
	{field} +restusername : String
	{field} +serverName : String
	{field} +username : String
}


class jConfigSerializing {
	{field} -configFile : File
	{field} +xmlName : String
	{method} -getConfigFilePath () : Path
	{method} +getCurrentConfigFile () : File
	{method} +load () : jConfig
	{method} +save ( paramjConfig1 : jConfig ) : void
}


class jCutCopyPaste {
	{field} +actionCopy : CopyAction
	{field} +actionCut : CutAction
	{field} +actionPaste : PasteAction
	{field} +actionSelectAll : SelectAllAction
	{field} -jMenuItemPopupCopy : JMenuItem
	{field} +jMenuItemPopupCut : JMenuItem
	{field} +jMenuItemPopupPaste : JMenuItem
	{field} -jMenuItemPopupSelectAll : JMenuItem
	{field} +jPopupMenu : JPopupMenu
	{field} -jSeparator1 : Separator
	{method} -initComponents () : void
	{method} -jMenuItemPopupCopyActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemPopupCutActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemPopupPasteActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemPopupSelectAllActionPerformed ( paramActionEvent1 : ActionEvent ) : void
}


class jMainFrame {
	{field} -duplicateCheck : JFrame
	{field} -jCheckBoxMenuItem1 : JCheckBoxMenuItem
	{field} #jCheckBoxMenuItemAutoRefresh : JCheckBoxMenuItem
	{field} -jMainMenuBar : JMenuBar
	{field} -jMenuEdit : JMenu
	{field} -jMenuFile : JMenu
	{field} -jMenuItem1 : JMenuItem
	{field} -jMenuItem2 : JMenuItem
	{field} -jMenuItemDuplicateCheck : JMenuItem
	{field} -jMenuItemEditCopy : JMenuItem
	{field} -jMenuItemEditCut : JMenuItem
	{field} -jMenuItemEditPaste : JMenuItem
	{field} -jMenuItemExit : JMenuItem
	{field} -jMenuItemMainPanel : JMenuItem
	{field} -jMenuItemResetAndRefresh : JMenuItem
	{field} -jMenuItemSelectAll : JMenuItem
	{field} -jMenuItemSetup : JMenuItem
	{field} -jMenuRefresh : JMenu
	{field} -jMenuWindow : JMenu
	{field} -jSeparator1 : Separator
	{field} -jSeparator3 : Separator
	{field} -mainPanelVisible : boolean
	{method} -Exit ( paramActionEvent1 : ActionEvent ) : void
	{method} -checkStateAutoRefresh () : void
	{method} +dispose () : void
	{method} +fullRefresh () : void
	{method} -initComponents () : void
	{method} -jCheckBoxMenuItemAutoRefreshActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemDuplicateCheckActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemEditCopyActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemEditCutActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemEditPasteActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemMainPanelActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemResetAndRefreshActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemSelectAllActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemSetupActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} +simpleRefresh () : void
	{method} +updateRowCountInfo () : void
}




JFrameDuplicateCheck -->  jCutCopyPaste : jCutCopyPaste
RestApiClient -->  RestApiClient : instance
Timer *--  jMainFrame : jmf
jMainFrame *--  Timer : timer
jMainFrame -->  JSetup : setup
jMainFrame -->  gridOnline : gridOnlinePanel
jMainFrame -->  jCutCopyPaste : jCutCopyPaste


@enduml