```plantuml
[plantuml,desktop-overview.puml.png,png]
----
@startuml

class Html2Text {
	{field} ~s : StringBuffer
	{method} +getText () : String
	{method} +handleText ( param[C1 : char[] , paramint2 : int ) : void
	{method} +parse ( paramReader1 : Reader ) : void
}


class JDialogDuplicateAutofix {
	{field} -duplicateRunAction : DuplicateRunAction
	{field} ~isCanceled : boolean
	{field} -jProgressBarDuplicateData : JProgressBar
	{field} -jProgressBarDuplicateSessions : JProgressBar
	{field} {static} -semaphore : Semaphore
	{method} -initComponents () : void
	{method} -jButtonCancelActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonRunActionPerformed ( paramActionEvent1 : ActionEvent ) : void
}


class JFrameDuplicateCheck {
	{field} -candidateAcctStopTime : String
	{field} -currentAcctStartTime : String
	{field} -currentFramedIPAddress : String
	{field} -currentRadAcctID : Long
	{field} -currentUsername : String
	{field} -jFormAutoFix : JDialog
	{method} -initComponents () : void
	{method} -jButtonRequestCorrectionActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemAutofixActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemCloseActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemCopyActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemCutActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemPasteActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemRefreshActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemSelectAllActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jTableDuplicateSessionsKeyReleased ( paramKeyEvent1 : KeyEvent ) : void
	{method} -jTableDuplicateSessionsLoadData () : void
	{method} -jTableDuplicateSessionsMouseClicked ( paramMouseEvent1 : MouseEvent ) : void
	{method} -jTableDuplicateSessionsSelectRow ( paramint1 : int ) : void
	{method} -jTableUsernameDetailKeyReleased ( paramKeyEvent1 : KeyEvent ) : void
	{method} -jTableUsernameDetailMouseClicked ( paramMouseEvent1 : MouseEvent ) : void
	{method} -jTableUsernameDetailSelectRow ( paramint1 : int ) : void
}


class JSetup {
	{field} -owner : JFrame
	{field} -setup : JFrame
	{method} -formWindowActivated ( paramWindowEvent1 : WindowEvent ) : void
	{method} -initComponents () : void
	{method} -jButtonCancelActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonDatabaseNameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonOkActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonPasswordActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonRESTPasswordActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonRESTServerNameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonRESTUsernameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonServerNameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonUsernameActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -loadConfig () : void
}


class Onlinemanager {
	{method}  {static} +main ( paramString;1 : String[] ) : void
}


class RestApiClient {
	{field} -baseUrl : String
	{field} -http : HttpClient
	{field} -mapper : ObjectMapper
	{field} -token : String
	{method} -buildRequest ( paramString1 : String , paramString2 : String ) : JsonNode
	{method} +correctionAcctStopTime ( paramLong1 : Long , paramString2 : String ) : RestApiClient
	{method}  {static} -encode ( paramString1 : String ) : String
	{method} +getAcctStopTimeCandidate ( paramString1 : String , paramString2 : String , paramString3 : String ) : ArrayList
	{method} +getAcctStopTimeCandidate ( paramDefaultTableModel1 : DefaultTableModel , paramString2 : String , paramString3 : String , paramString4 : String ) : RestApiClient
	{method} +getData ( paramDefaultTableModel1 : DefaultTableModel , paramint2 : int , paramboolean3 : boolean , paramint4 : int , paramString5 : String , paramString6 : String ) : RestApiClient
	{method} +getDuplicateData () : ArrayList
	{method} +getDuplicateData ( paramDefaultTableModel1 : DefaultTableModel ) : RestApiClient
	{method} +getDuplicateSessions ( paramString1 : String ) : ArrayList
	{method} +getDuplicateSessions ( paramDefaultTableModel1 : DefaultTableModel , paramString2 : String ) : RestApiClient
	{method} +login ( paramString1 : String , paramString2 : String ) : boolean
	{method} +logout () : void
	{method} -post ( paramString1 : String , paramString2 : String ) : JsonNode
	{method}  {static} -text ( paramJsonNode1 : JsonNode , paramString2 : String ) : String
}


class Timer {
	{field} -timer : Timer
	{method} +start () : void
	{method} +stop () : void
}


class VersionChecker {
	{field} {static} -GITHUB_API_URL : String
	{field} {static} -RELEASES_URL : String
	{method}  {static} +checkForUpdates ( paramJFrame1 : JFrame ) : void
	{method}  {static} -extractTagFromJson ( paramString1 : String ) : String
	{method}  {static} +getCurrentVersion () : String
	{method}  {static} -isNewerVersion ( paramString1 : String , paramString2 : String ) : boolean
	{method}  {static} -openInBrowser ( paramString1 : String ) : void
}


class gridOnline {
	{field} +jWhereOperation : JComboBox
	{method} -initComponents () : void
	{method} -jButtonClearCustomerFilterActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonRefreshActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jButtonUsernameAndFramedIPFilterActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jCheckBoxOnlineActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jTableOnlineKeyReleased ( paramKeyEvent1 : KeyEvent ) : void
	{method} -jTableOnlineMouseClicked ( paramMouseEvent1 : MouseEvent ) : void
	{method} +jTableOnlineSelectRow ( paramint1 : int ) : void
	{method} +loadData () : void
	{method} +showCell ( paramint1 : int , paramint2 : int ) : int
	{method} +updateRowCountInfo () : void
}


class jConfig {
	{field} +databaseName : String
	{field} +password : String
	{field} +restApiUrl : String
	{field} +restpassword : String
	{field} +restserverName : String
	{field} +restusername : String
	{field} +serverName : String
	{field} +username : String
}


class jConfigSerializing {
	{field} -configFile : File
	{field} +xmlName : String
	{method} -getConfigFilePath () : Path
	{method} +getCurrentConfigFile () : File
	{method} +load () : jConfig
	{method} +save ( paramjConfig1 : jConfig ) : void
}


class jCutCopyPaste {
	{field} +actionCopy : CopyAction
	{field} +actionCut : CutAction
	{field} +actionPaste : PasteAction
	{field} +actionSelectAll : SelectAllAction
	{field} +jPopupMenu : JPopupMenu
	{method} -initComponents () : void
	{method} -jMenuItemPopupCopyActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemPopupCutActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemPopupPasteActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemPopupSelectAllActionPerformed ( paramActionEvent1 : ActionEvent ) : void
}


class jMainFrame {
	{field} -duplicateCheck : JFrame
	{field} -jMainMenuBar : JMenuBar
	{field} -mainPanelVisible : boolean
	{method} -Exit ( paramActionEvent1 : ActionEvent ) : void
	{method} -checkStateAutoRefresh () : void
	{method} +dispose () : void
	{method} +fullRefresh () : void
	{method} -initComponents () : void
	{method} -jCheckBoxMenuItemAutoRefreshActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemDuplicateCheckActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemEditCopyActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemEditCutActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemEditPasteActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemMainPanelActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemResetAndRefreshActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemSelectAllActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} -jMenuItemSetupActionPerformed ( paramActionEvent1 : ActionEvent ) : void
	{method} +simpleRefresh () : void
	{method} +updateRowCountInfo () : void
}




JFrameDuplicateCheck -->  jCutCopyPaste : jCutCopyPaste
RestApiClient -->  RestApiClient : instance
Timer *--  jMainFrame : jmf
jMainFrame *--  Timer : timer
jMainFrame -->  JSetup : setup
jMainFrame -->  gridOnline : gridOnlinePanel
jMainFrame -->  jCutCopyPaste : jCutCopyPaste


@enduml
----
```
